lsi: false
safe: true
source: /qdot
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
production_url : http://marcosj.github.io/qdot
BASE_PATH : http://marcosj.github.io/qdot	
