lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
markdown: kramdown
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
production_url : http://marcosj.github.io/qdot
BASE_PATH : http://marcosj.github.io/qdot	
